insert into cities (city_id, name, state_id) values (1, 'Núi Sập', 151);
insert into cities (city_id, name, state_id) values (2, 'Onzaga', 40);
insert into cities (city_id, name, state_id) values (3, 'Jinhua', 149);
insert into cities (city_id, name, state_id) values (4, 'Falköping', 85);
insert into cities (city_id, name, state_id) values (5, 'Pedra Furada', 191);
insert into cities (city_id, name, state_id) values (6, 'Domampot', 170);
insert into cities (city_id, name, state_id) values (7, 'Daduo', 24);
insert into cities (city_id, name, state_id) values (8, 'Novopokrovka', 175);
insert into cities (city_id, name, state_id) values (9, 'Huangbu', 59);
insert into cities (city_id, name, state_id) values (10, 'Fuyong', 22);
insert into cities (city_id, name, state_id) values (11, 'Murça', 63);
insert into cities (city_id, name, state_id) values (12, 'Sydney Mines', 20);
insert into cities (city_id, name, state_id) values (13, 'Komorów', 124);
insert into cities (city_id, name, state_id) values (14, 'Montluel', 162);
insert into cities (city_id, name, state_id) values (15, 'Vilca', 28);
insert into cities (city_id, name, state_id) values (16, 'Butwāl', 44);
insert into cities (city_id, name, state_id) values (17, 'Gœsdorf', 175);
insert into cities (city_id, name, state_id) values (18, 'San Diego', 94);
insert into cities (city_id, name, state_id) values (19, 'Cuihuangkou', 11);
insert into cities (city_id, name, state_id) values (20, 'Baleal', 37);
insert into cities (city_id, name, state_id) values (21, 'Mahdishahr', 48);
insert into cities (city_id, name, state_id) values (22, 'Qasr Abu Hadi', 175);
insert into cities (city_id, name, state_id) values (23, 'Medveditskiy', 135);
insert into cities (city_id, name, state_id) values (24, 'Condado', 149);
insert into cities (city_id, name, state_id) values (25, 'Arevik', 20);
insert into cities (city_id, name, state_id) values (26, 'Quxi', 129);
insert into cities (city_id, name, state_id) values (27, 'Dukuhsia', 82);
insert into cities (city_id, name, state_id) values (28, 'Poxi', 155);
insert into cities (city_id, name, state_id) values (29, 'Tubigan', 192);
insert into cities (city_id, name, state_id) values (30, 'Qincheng', 90);
insert into cities (city_id, name, state_id) values (31, 'Lantang', 97);
insert into cities (city_id, name, state_id) values (32, 'Malasugui', 159);
insert into cities (city_id, name, state_id) values (33, 'Huangmao', 14);
insert into cities (city_id, name, state_id) values (34, 'Palmeira', 150);
insert into cities (city_id, name, state_id) values (35, 'Caiyuan', 117);
insert into cities (city_id, name, state_id) values (36, 'Najin', 39);
insert into cities (city_id, name, state_id) values (37, 'Solna', 5);
insert into cities (city_id, name, state_id) values (38, 'Yangp''yŏng', 61);
insert into cities (city_id, name, state_id) values (39, 'Garupá', 187);
insert into cities (city_id, name, state_id) values (40, 'Salcedo', 71);
insert into cities (city_id, name, state_id) values (41, 'Xiangyang', 197);
insert into cities (city_id, name, state_id) values (42, 'Borucin', 166);
insert into cities (city_id, name, state_id) values (43, 'Pehčevo', 121);
insert into cities (city_id, name, state_id) values (44, 'Kotingnatagete', 123);
insert into cities (city_id, name, state_id) values (45, 'Chuanxi', 114);
insert into cities (city_id, name, state_id) values (46, 'Tierimu', 130);
insert into cities (city_id, name, state_id) values (47, 'Roblin', 100);
insert into cities (city_id, name, state_id) values (48, 'Okiot', 80);
insert into cities (city_id, name, state_id) values (49, 'Chichibu', 12);
insert into cities (city_id, name, state_id) values (50, 'Wang Muang', 36);
insert into cities (city_id, name, state_id) values (51, 'Beaumont', 48);
insert into cities (city_id, name, state_id) values (52, 'Łazy', 123);
insert into cities (city_id, name, state_id) values (53, 'Villa Nueva', 153);
insert into cities (city_id, name, state_id) values (54, 'Kafr Zaytā', 192);
insert into cities (city_id, name, state_id) values (55, 'Chã', 79);
insert into cities (city_id, name, state_id) values (56, 'Altavista', 20);
insert into cities (city_id, name, state_id) values (57, 'Ngulahan', 52);
insert into cities (city_id, name, state_id) values (58, 'Gununganyar', 58);
insert into cities (city_id, name, state_id) values (59, 'Franca', 129);
insert into cities (city_id, name, state_id) values (60, 'Meru', 45);
insert into cities (city_id, name, state_id) values (61, 'Valenciennes', 43);
insert into cities (city_id, name, state_id) values (62, 'Jiefu', 29);
insert into cities (city_id, name, state_id) values (63, 'Benešov', 102);
insert into cities (city_id, name, state_id) values (64, 'Tayu', 66);
insert into cities (city_id, name, state_id) values (65, 'Tipolo', 174);
insert into cities (city_id, name, state_id) values (66, 'Itako', 154);
insert into cities (city_id, name, state_id) values (67, 'Täby', 50);
insert into cities (city_id, name, state_id) values (68, 'Barrhead', 103);
insert into cities (city_id, name, state_id) values (69, 'Fenghua', 173);
insert into cities (city_id, name, state_id) values (70, 'Mogapi', 132);
insert into cities (city_id, name, state_id) values (71, 'Sangallaya', 136);
insert into cities (city_id, name, state_id) values (72, 'Jindong', 48);
insert into cities (city_id, name, state_id) values (73, 'Maciejowice', 197);
insert into cities (city_id, name, state_id) values (74, 'Kampala', 96);
insert into cities (city_id, name, state_id) values (75, 'Toyama-shi', 196);
insert into cities (city_id, name, state_id) values (76, 'Qingyang', 14);
insert into cities (city_id, name, state_id) values (77, 'Nenotes', 140);
insert into cities (city_id, name, state_id) values (78, 'Helsingborg', 21);
insert into cities (city_id, name, state_id) values (79, 'Izmaylovo', 193);
insert into cities (city_id, name, state_id) values (80, 'Karangmulyo', 29);
insert into cities (city_id, name, state_id) values (81, 'Ghazni', 112);
insert into cities (city_id, name, state_id) values (82, 'Nanyuan', 18);
insert into cities (city_id, name, state_id) values (83, 'Ebute Ikorodu', 123);
insert into cities (city_id, name, state_id) values (84, 'Sá', 53);
insert into cities (city_id, name, state_id) values (85, 'Qingshan', 54);
insert into cities (city_id, name, state_id) values (86, 'Beiqijia', 21);
insert into cities (city_id, name, state_id) values (87, 'Ochojno', 8);
insert into cities (city_id, name, state_id) values (88, 'Bailieborough', 161);
insert into cities (city_id, name, state_id) values (89, 'Leticia', 142);
insert into cities (city_id, name, state_id) values (90, 'Sobreira', 162);
insert into cities (city_id, name, state_id) values (91, 'Buenos Aires', 56);
insert into cities (city_id, name, state_id) values (92, 'Sydney', 35);
insert into cities (city_id, name, state_id) values (93, 'Pasirgaru', 83);
insert into cities (city_id, name, state_id) values (94, 'Madoi', 161);
insert into cities (city_id, name, state_id) values (95, 'Sumqayıt', 173);
insert into cities (city_id, name, state_id) values (96, 'Perjuangan', 170);
insert into cities (city_id, name, state_id) values (97, 'Dolní Dvořiště', 128);
insert into cities (city_id, name, state_id) values (98, 'Lunas', 99);
insert into cities (city_id, name, state_id) values (99, 'Changsu', 82);
insert into cities (city_id, name, state_id) values (100, 'Hejiang', 189);
insert into cities (city_id, name, state_id) values (101, 'Harstad', 39);
insert into cities (city_id, name, state_id) values (102, 'Lengkeng', 73);
insert into cities (city_id, name, state_id) values (103, 'Fontvieille', 14);
insert into cities (city_id, name, state_id) values (104, 'Picton', 1);
insert into cities (city_id, name, state_id) values (105, 'Nemyriv', 8);
insert into cities (city_id, name, state_id) values (106, 'Zdovbytsya', 161);
insert into cities (city_id, name, state_id) values (107, 'Sawara', 13);
insert into cities (city_id, name, state_id) values (108, 'New Sibonga', 147);
insert into cities (city_id, name, state_id) values (109, 'Bishkek', 114);
insert into cities (city_id, name, state_id) values (110, 'Cristóbal', 62);
insert into cities (city_id, name, state_id) values (111, 'Volosovo', 130);
insert into cities (city_id, name, state_id) values (112, 'Ḩuraytān', 162);
insert into cities (city_id, name, state_id) values (113, 'Kokubunji', 162);
insert into cities (city_id, name, state_id) values (114, 'Huaidian', 129);
insert into cities (city_id, name, state_id) values (115, 'Yanggu', 155);
insert into cities (city_id, name, state_id) values (116, 'Marseille', 3);
insert into cities (city_id, name, state_id) values (117, 'Kaz', 120);
insert into cities (city_id, name, state_id) values (118, 'Ayía Triás', 42);
insert into cities (city_id, name, state_id) values (119, 'Mérignac', 194);
insert into cities (city_id, name, state_id) values (120, 'Imsil', 120);
insert into cities (city_id, name, state_id) values (121, 'Am Djarass', 98);
insert into cities (city_id, name, state_id) values (122, 'Vis', 74);
insert into cities (city_id, name, state_id) values (123, 'Bystryanka', 174);
insert into cities (city_id, name, state_id) values (124, 'Athlone', 95);
insert into cities (city_id, name, state_id) values (125, 'Dologon', 166);
insert into cities (city_id, name, state_id) values (126, 'Guanzhou', 197);
insert into cities (city_id, name, state_id) values (127, 'Mabini', 52);
insert into cities (city_id, name, state_id) values (128, 'Iúna', 121);
insert into cities (city_id, name, state_id) values (129, 'Osa', 55);
insert into cities (city_id, name, state_id) values (130, 'Lazaro Cardenas', 156);
insert into cities (city_id, name, state_id) values (131, 'Jessore', 177);
insert into cities (city_id, name, state_id) values (132, 'Jarada', 96);
insert into cities (city_id, name, state_id) values (133, 'Asaita', 96);
insert into cities (city_id, name, state_id) values (134, 'Itinga', 117);
insert into cities (city_id, name, state_id) values (135, 'Vancouver', 135);
insert into cities (city_id, name, state_id) values (136, 'Al Madīd', 70);
insert into cities (city_id, name, state_id) values (137, 'Songkar B', 37);
insert into cities (city_id, name, state_id) values (138, 'Debrecen', 27);
insert into cities (city_id, name, state_id) values (139, 'Venezia', 43);
insert into cities (city_id, name, state_id) values (140, 'Sviadnov', 109);
insert into cities (city_id, name, state_id) values (141, 'Garça', 21);
insert into cities (city_id, name, state_id) values (142, 'Orléans', 67);
insert into cities (city_id, name, state_id) values (143, 'Jayapura', 173);
insert into cities (city_id, name, state_id) values (144, 'Vawkavysk', 95);
insert into cities (city_id, name, state_id) values (145, 'Zarasai', 120);
insert into cities (city_id, name, state_id) values (146, 'Caldas', 93);
insert into cities (city_id, name, state_id) values (147, 'Santa Catalina', 143);
insert into cities (city_id, name, state_id) values (148, 'São José do Egito', 197);
insert into cities (city_id, name, state_id) values (149, 'Gevgelija', 7);
insert into cities (city_id, name, state_id) values (150, 'Yefremov', 65);
insert into cities (city_id, name, state_id) values (151, 'Strasbourg', 124);
insert into cities (city_id, name, state_id) values (152, 'Nakusp', 161);
insert into cities (city_id, name, state_id) values (153, 'Curiapo', 146);
insert into cities (city_id, name, state_id) values (154, 'São Bartolomeu', 176);
insert into cities (city_id, name, state_id) values (155, 'Wushi', 5);
insert into cities (city_id, name, state_id) values (156, 'Mtwara', 151);
insert into cities (city_id, name, state_id) values (157, 'Brušperk', 159);
insert into cities (city_id, name, state_id) values (158, 'Saint-Priest-en-Jarez', 81);
insert into cities (city_id, name, state_id) values (159, 'Hannō', 155);
insert into cities (city_id, name, state_id) values (160, 'Yongjiu', 36);
insert into cities (city_id, name, state_id) values (161, 'Tekik Wetan', 177);
insert into cities (city_id, name, state_id) values (162, 'Busungbiu', 45);
insert into cities (city_id, name, state_id) values (163, 'Santa Rosa', 68);
insert into cities (city_id, name, state_id) values (164, 'Santa Cruz', 33);
insert into cities (city_id, name, state_id) values (165, 'Parravak’ar', 66);
insert into cities (city_id, name, state_id) values (166, 'Alasmalang', 65);
insert into cities (city_id, name, state_id) values (167, 'Campos Gerais', 89);
insert into cities (city_id, name, state_id) values (168, 'Helong', 89);
insert into cities (city_id, name, state_id) values (169, 'Dois Vizinhos', 123);
insert into cities (city_id, name, state_id) values (170, 'Changzheng', 67);
insert into cities (city_id, name, state_id) values (171, 'Golek', 77);
insert into cities (city_id, name, state_id) values (172, 'São Paio de Seide', 67);
insert into cities (city_id, name, state_id) values (173, 'Połajewo', 174);
insert into cities (city_id, name, state_id) values (174, 'Chengguan', 136);
insert into cities (city_id, name, state_id) values (175, 'Takaoka', 30);
insert into cities (city_id, name, state_id) values (176, 'Évora', 139);
insert into cities (city_id, name, state_id) values (177, 'Mojokerto', 38);
insert into cities (city_id, name, state_id) values (178, 'Binulasan', 29);
insert into cities (city_id, name, state_id) values (179, 'Åhus', 75);
insert into cities (city_id, name, state_id) values (180, 'Litvínov', 113);
insert into cities (city_id, name, state_id) values (181, 'Srubec', 193);
insert into cities (city_id, name, state_id) values (182, 'Prómachoi', 159);
insert into cities (city_id, name, state_id) values (183, 'Ilek', 78);
insert into cities (city_id, name, state_id) values (184, 'Radviliskis', 98);
insert into cities (city_id, name, state_id) values (185, 'Trondheim', 79);
insert into cities (city_id, name, state_id) values (186, 'Brak', 110);
insert into cities (city_id, name, state_id) values (187, 'Tapilon', 157);
insert into cities (city_id, name, state_id) values (188, 'Catu', 120);
insert into cities (city_id, name, state_id) values (189, 'Binonga', 25);
insert into cities (city_id, name, state_id) values (190, 'Phra Pradaeng', 142);
insert into cities (city_id, name, state_id) values (191, 'Chesma', 5);
insert into cities (city_id, name, state_id) values (192, 'Shoushan', 95);
insert into cities (city_id, name, state_id) values (193, 'Tabio', 71);
insert into cities (city_id, name, state_id) values (194, 'Minyat an Naşr', 128);
insert into cities (city_id, name, state_id) values (195, 'Gunung Timur', 32);
insert into cities (city_id, name, state_id) values (196, 'Putre', 3);
insert into cities (city_id, name, state_id) values (197, 'Đưc Trọng', 98);
insert into cities (city_id, name, state_id) values (198, 'Slantsy', 163);
insert into cities (city_id, name, state_id) values (199, 'Zhangjiachang', 171);
insert into cities (city_id, name, state_id) values (200, 'Shangrao', 165);
