insert into states (state_id, name, country_id) values (1, 'North Carolina', 192);
insert into states (state_id, name, country_id) values (2, 'Virginia', 195);
insert into states (state_id, name, country_id) values (3, 'South Carolina', 201);
insert into states (state_id, name, country_id) values (4, 'New York', 67);
insert into states (state_id, name, country_id) values (5, 'Florida', 20);
insert into states (state_id, name, country_id) values (6, 'California', 56);
insert into states (state_id, name, country_id) values (7, 'Kentucky', 233);
insert into states (state_id, name, country_id) values (8, 'Ohio', 123);
insert into states (state_id, name, country_id) values (9, 'Texas', 189);
insert into states (state_id, name, country_id) values (10, 'Texas', 215);
insert into states (state_id, name, country_id) values (11, 'Minnesota', 219);
insert into states (state_id, name, country_id) values (12, 'Ohio', 175);
insert into states (state_id, name, country_id) values (13, 'Iowa', 61);
insert into states (state_id, name, country_id) values (14, 'West Virginia', 9);
insert into states (state_id, name, country_id) values (15, 'Texas', 30);
insert into states (state_id, name, country_id) values (16, 'Texas', 226);
insert into states (state_id, name, country_id) values (17, 'New York', 57);
insert into states (state_id, name, country_id) values (18, 'Illinois', 219);
insert into states (state_id, name, country_id) values (19, 'New Hampshire', 26);
insert into states (state_id, name, country_id) values (20, 'Tennessee', 83);
insert into states (state_id, name, country_id) values (21, 'California', 38);
insert into states (state_id, name, country_id) values (22, 'Florida', 159);
insert into states (state_id, name, country_id) values (23, 'Massachusetts', 61);
insert into states (state_id, name, country_id) values (24, 'Florida', 32);
insert into states (state_id, name, country_id) values (25, 'Ohio', 117);
insert into states (state_id, name, country_id) values (26, 'Virginia', 49);
insert into states (state_id, name, country_id) values (27, 'Texas', 154);
insert into states (state_id, name, country_id) values (28, 'Florida', 33);
insert into states (state_id, name, country_id) values (29, 'New York', 217);
insert into states (state_id, name, country_id) values (30, 'Georgia', 36);
insert into states (state_id, name, country_id) values (31, 'Oklahoma', 124);
insert into states (state_id, name, country_id) values (32, 'District of Columbia', 109);
insert into states (state_id, name, country_id) values (33, 'North Carolina', 177);
insert into states (state_id, name, country_id) values (34, 'Texas', 153);
insert into states (state_id, name, country_id) values (35, 'California', 29);
insert into states (state_id, name, country_id) values (36, 'North Carolina', 65);
insert into states (state_id, name, country_id) values (37, 'California', 4);
insert into states (state_id, name, country_id) values (38, 'New York', 111);
insert into states (state_id, name, country_id) values (39, 'Florida', 94);
insert into states (state_id, name, country_id) values (40, 'California', 74);
insert into states (state_id, name, country_id) values (41, 'Virginia', 246);
insert into states (state_id, name, country_id) values (42, 'Minnesota', 53);
insert into states (state_id, name, country_id) values (43, 'New Mexico', 90);
insert into states (state_id, name, country_id) values (44, 'Florida', 165);
insert into states (state_id, name, country_id) values (45, 'Florida', 211);
insert into states (state_id, name, country_id) values (46, 'New York', 136);
insert into states (state_id, name, country_id) values (47, 'California', 80);
insert into states (state_id, name, country_id) values (48, 'Texas', 218);
insert into states (state_id, name, country_id) values (49, 'Georgia', 238);
insert into states (state_id, name, country_id) values (50, 'Indiana', 29);
insert into states (state_id, name, country_id) values (51, 'California', 55);
insert into states (state_id, name, country_id) values (52, 'Utah', 130);
insert into states (state_id, name, country_id) values (53, 'California', 203);
insert into states (state_id, name, country_id) values (54, 'Ohio', 130);
insert into states (state_id, name, country_id) values (55, 'California', 202);
insert into states (state_id, name, country_id) values (56, 'District of Columbia', 23);
insert into states (state_id, name, country_id) values (57, 'Nebraska', 17);
insert into states (state_id, name, country_id) values (58, 'Colorado', 112);
insert into states (state_id, name, country_id) values (59, 'Colorado', 176);
insert into states (state_id, name, country_id) values (60, 'Wisconsin', 83);
insert into states (state_id, name, country_id) values (61, 'Ohio', 204);
insert into states (state_id, name, country_id) values (62, 'Ohio', 127);
insert into states (state_id, name, country_id) values (63, 'Florida', 130);
insert into states (state_id, name, country_id) values (64, 'Washington', 53);
insert into states (state_id, name, country_id) values (65, 'Georgia', 138);
insert into states (state_id, name, country_id) values (66, 'Nebraska', 23);
insert into states (state_id, name, country_id) values (67, 'Florida', 19);
insert into states (state_id, name, country_id) values (68, 'Texas', 20);
insert into states (state_id, name, country_id) values (69, 'Texas', 242);
insert into states (state_id, name, country_id) values (70, 'Texas', 1);
insert into states (state_id, name, country_id) values (71, 'Florida', 202);
insert into states (state_id, name, country_id) values (72, 'Indiana', 159);
insert into states (state_id, name, country_id) values (73, 'North Carolina', 80);
insert into states (state_id, name, country_id) values (74, 'Utah', 155);
insert into states (state_id, name, country_id) values (75, 'Ohio', 239);
insert into states (state_id, name, country_id) values (76, 'Ohio', 92);
insert into states (state_id, name, country_id) values (77, 'New York', 25);
insert into states (state_id, name, country_id) values (78, 'South Carolina', 81);
insert into states (state_id, name, country_id) values (79, 'Louisiana', 200);
insert into states (state_id, name, country_id) values (80, 'Texas', 37);
insert into states (state_id, name, country_id) values (81, 'Florida', 135);
insert into states (state_id, name, country_id) values (82, 'Texas', 31);
insert into states (state_id, name, country_id) values (83, 'Pennsylvania', 33);
insert into states (state_id, name, country_id) values (84, 'North Carolina', 137);
insert into states (state_id, name, country_id) values (85, 'Texas', 77);
insert into states (state_id, name, country_id) values (86, 'Oregon', 139);
insert into states (state_id, name, country_id) values (87, 'California', 68);
insert into states (state_id, name, country_id) values (88, 'Texas', 111);
insert into states (state_id, name, country_id) values (89, 'Texas', 203);
insert into states (state_id, name, country_id) values (90, 'Texas', 23);
insert into states (state_id, name, country_id) values (91, 'New York', 2);
insert into states (state_id, name, country_id) values (92, 'California', 53);
insert into states (state_id, name, country_id) values (93, 'Texas', 240);
insert into states (state_id, name, country_id) values (94, 'California', 185);
insert into states (state_id, name, country_id) values (95, 'Texas', 130);
insert into states (state_id, name, country_id) values (96, 'Florida', 142);
insert into states (state_id, name, country_id) values (97, 'Ohio', 146);
insert into states (state_id, name, country_id) values (98, 'Kentucky', 39);
insert into states (state_id, name, country_id) values (99, 'Idaho', 213);
insert into states (state_id, name, country_id) values (100, 'California', 203);
insert into states (state_id, name, country_id) values (101, 'Michigan', 131);
insert into states (state_id, name, country_id) values (102, 'Hawaii', 228);
insert into states (state_id, name, country_id) values (103, 'Florida', 199);
insert into states (state_id, name, country_id) values (104, 'Minnesota', 15);
insert into states (state_id, name, country_id) values (105, 'Texas', 4);
insert into states (state_id, name, country_id) values (106, 'District of Columbia', 183);
insert into states (state_id, name, country_id) values (107, 'Colorado', 191);
insert into states (state_id, name, country_id) values (108, 'California', 116);
insert into states (state_id, name, country_id) values (109, 'North Carolina', 151);
insert into states (state_id, name, country_id) values (110, 'Iowa', 122);
insert into states (state_id, name, country_id) values (111, 'Florida', 183);
insert into states (state_id, name, country_id) values (112, 'Minnesota', 4);
insert into states (state_id, name, country_id) values (113, 'California', 108);
insert into states (state_id, name, country_id) values (114, 'Montana', 35);
insert into states (state_id, name, country_id) values (115, 'California', 64);
insert into states (state_id, name, country_id) values (116, 'Georgia', 187);
insert into states (state_id, name, country_id) values (117, 'Texas', 213);
insert into states (state_id, name, country_id) values (118, 'Massachusetts', 233);
insert into states (state_id, name, country_id) values (119, 'Massachusetts', 112);
insert into states (state_id, name, country_id) values (120, 'New York', 101);
insert into states (state_id, name, country_id) values (121, 'Kansas', 55);
insert into states (state_id, name, country_id) values (122, 'Florida', 144);
insert into states (state_id, name, country_id) values (123, 'Minnesota', 153);
insert into states (state_id, name, country_id) values (124, 'Ohio', 68);
insert into states (state_id, name, country_id) values (125, 'Connecticut', 61);
insert into states (state_id, name, country_id) values (126, 'California', 76);
insert into states (state_id, name, country_id) values (127, 'Texas', 230);
insert into states (state_id, name, country_id) values (128, 'Kansas', 189);
insert into states (state_id, name, country_id) values (129, 'Wisconsin', 26);
insert into states (state_id, name, country_id) values (130, 'California', 158);
insert into states (state_id, name, country_id) values (131, 'Arizona', 144);
insert into states (state_id, name, country_id) values (132, 'California', 91);
insert into states (state_id, name, country_id) values (133, 'California', 126);
insert into states (state_id, name, country_id) values (134, 'Alabama', 34);
insert into states (state_id, name, country_id) values (135, 'Connecticut', 192);
insert into states (state_id, name, country_id) values (136, 'California', 169);
insert into states (state_id, name, country_id) values (137, 'Colorado', 68);
insert into states (state_id, name, country_id) values (138, 'Georgia', 23);
insert into states (state_id, name, country_id) values (139, 'Florida', 184);
insert into states (state_id, name, country_id) values (140, 'Virginia', 140);
insert into states (state_id, name, country_id) values (141, 'Florida', 95);
insert into states (state_id, name, country_id) values (142, 'Louisiana', 43);
insert into states (state_id, name, country_id) values (143, 'Texas', 13);
insert into states (state_id, name, country_id) values (144, 'South Carolina', 195);
insert into states (state_id, name, country_id) values (145, 'California', 196);
insert into states (state_id, name, country_id) values (146, 'Texas', 127);
insert into states (state_id, name, country_id) values (147, 'North Dakota', 150);
insert into states (state_id, name, country_id) values (148, 'District of Columbia', 88);
insert into states (state_id, name, country_id) values (149, 'Georgia', 177);
insert into states (state_id, name, country_id) values (150, 'Pennsylvania', 206);
insert into states (state_id, name, country_id) values (151, 'New York', 36);
insert into states (state_id, name, country_id) values (152, 'Virginia', 221);
insert into states (state_id, name, country_id) values (153, 'Florida', 162);
insert into states (state_id, name, country_id) values (154, 'Indiana', 57);
insert into states (state_id, name, country_id) values (155, 'Maryland', 220);
insert into states (state_id, name, country_id) values (156, 'Florida', 219);
insert into states (state_id, name, country_id) values (157, 'Arkansas', 232);
insert into states (state_id, name, country_id) values (158, 'California', 57);
insert into states (state_id, name, country_id) values (159, 'Michigan', 225);
insert into states (state_id, name, country_id) values (160, 'Illinois', 238);
insert into states (state_id, name, country_id) values (161, 'Louisiana', 103);
insert into states (state_id, name, country_id) values (162, 'Alabama', 146);
insert into states (state_id, name, country_id) values (163, 'Texas', 108);
insert into states (state_id, name, country_id) values (164, 'Florida', 242);
insert into states (state_id, name, country_id) values (165, 'Connecticut', 206);
insert into states (state_id, name, country_id) values (166, 'Alabama', 78);
insert into states (state_id, name, country_id) values (167, 'Minnesota', 197);
insert into states (state_id, name, country_id) values (168, 'California', 53);
insert into states (state_id, name, country_id) values (169, 'Florida', 13);
insert into states (state_id, name, country_id) values (170, 'Oklahoma', 140);
insert into states (state_id, name, country_id) values (171, 'Ohio', 250);
insert into states (state_id, name, country_id) values (172, 'Indiana', 135);
insert into states (state_id, name, country_id) values (173, 'New York', 131);
insert into states (state_id, name, country_id) values (174, 'New York', 127);
insert into states (state_id, name, country_id) values (175, 'Florida', 83);
insert into states (state_id, name, country_id) values (176, 'Indiana', 159);
insert into states (state_id, name, country_id) values (177, 'Minnesota', 195);
insert into states (state_id, name, country_id) values (178, 'New York', 168);
insert into states (state_id, name, country_id) values (179, 'Oregon', 214);
insert into states (state_id, name, country_id) values (180, 'Colorado', 128);
insert into states (state_id, name, country_id) values (181, 'Minnesota', 92);
insert into states (state_id, name, country_id) values (182, 'Georgia', 53);
insert into states (state_id, name, country_id) values (183, 'Mississippi', 5);
insert into states (state_id, name, country_id) values (184, 'Arkansas', 94);
insert into states (state_id, name, country_id) values (185, 'Florida', 61);
insert into states (state_id, name, country_id) values (186, 'Louisiana', 27);
insert into states (state_id, name, country_id) values (187, 'Texas', 163);
insert into states (state_id, name, country_id) values (188, 'Michigan', 84);
insert into states (state_id, name, country_id) values (189, 'Pennsylvania', 108);
insert into states (state_id, name, country_id) values (190, 'Pennsylvania', 22);
insert into states (state_id, name, country_id) values (191, 'Louisiana', 48);
insert into states (state_id, name, country_id) values (192, 'Virginia', 154);
insert into states (state_id, name, country_id) values (193, 'Indiana', 53);
insert into states (state_id, name, country_id) values (194, 'Missouri', 25);
insert into states (state_id, name, country_id) values (195, 'Texas', 104);
insert into states (state_id, name, country_id) values (196, 'Indiana', 153);
insert into states (state_id, name, country_id) values (197, 'Texas', 124);
insert into states (state_id, name, country_id) values (198, 'Florida', 124);
insert into states (state_id, name, country_id) values (199, 'Iowa', 77);
insert into states (state_id, name, country_id) values (200, 'Minnesota', 213);
